### ISSUE TITLE
torchfile.T7ReaderException: unknown object type / typeidx: -1112529805

### ISSUE THREAD

**Issue by harbarex** [bshillingford/python-torchfile#18]
Error in loading a .t7 file

```
Traceback (most recent call last):
  File "main.py", line 77, in <module>
    algo.sample(datapath, cfg.STAGE)
  File "C:\Users\Ankit\Desktop\EAD Project\StackGAN-Pytorch-master\code\trainer.py", line 242, in sample
    t_file = torchfile.load(datapath)
  File "C:\Users\Ankit\Anaconda3\lib\site-packages\torchfile.py", line 424, in load
    return reader.read_obj()
  File "C:\Users\Ankit\Anaconda3\lib\site-packages\torchfile.py", line 386, in read_obj
    v = self.read_obj()
  File "C:\Users\Ankit\Anaconda3\lib\site-packages\torchfile.py", line 386, in read_obj
    v = self.read_obj()
  File "C:\Users\Ankit\Anaconda3\lib\site-packages\torchfile.py", line 414, in read_obj
    "unknown object type / typeidx: {}".format(typeidx))
torchfile.T7ReaderException: unknown object type / typeidx: -1112529805
```

**Comment by masoudpz** [comment]
I've gotten this error too, where is the problem?
